{% set name = "skyfield" %}
{% set version = "1.51" %}
{% set sha256 = "afebb71a86ff1049885133120f9149a54ed2d8b38721307eeb0e0a93ca73aafc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python  {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - jplephem >=2.13
    - sgp4 >=2.13
    - certifi >=2017.4.17

test:
  requires:
    - python {{ python_min }}
    - mock
    - pip
    - wget
    - pandas
    - pytz
    - git
  imports:
    - skyfield
    - skyfield.data
    - skyfield.tests
  commands:
    - pip install https://github.com/brandon-rhodes/assay/archive/master.zip
    - git clone https://github.com/skyfielders/python-skyfield.git
    - cd python-skyfield
    - git checkout {{ version }}
    - cd ci
    - assay --batch skyfield.tests
    - cd ..
    - cd ..

about:
  home: http://rhodesmill.org/skyfield/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Elegant astronomy for Python

  description: |
    Skyfield computes positions for the stars, planets, and satellites in orbit around the Earth. 
    Its results should agree with the positions generated by the United States Naval Observatory 
    and their Astronomical Almanac to within 0.0005 arcseconds (which equals half a milliarcsecond). 
    Written in pure Python and installs without any compilation.
    Supports Python 2.6-2.7 and Python 3.3-3.6. Has NumPy as its only binary dependency, 
    the fundamental package for scientific computing with Python, whose vector operations make 
    Skyfield efficient.  
  doc_url: http://rhodesmill.org/skyfield/toc.html
  dev_url: https://github.com/skyfielders/python-skyfield

extra:
  recipe-maintainers:
    - jochym
    - brandon-rhodes
