travis:
  secure:
    BINSTAR_TOKEN: nNspGFWiZEIzQ7hy42uMYaDbQgKjY01bEKO4qB1gYoGUMXGmoj+jCEDEK90895do99v+yDqsgoZDGhVSJhTSbhAGH2TJz4PW7R5j9d7XN5RWc9ZWXzSCoyY3se1P59Jrj/xyMjwrhkwKYoTEtEpv8Ufal35jjRRn59N2KWVc36eRO/qZZscDeBipI1aIS7GyVQnVil2SsQCvRviTnGUVCz5drhXctAK+YbtABBcix0Ye/JV96fN+cIOz/AnMUVvlipIaIuwUSXj9OLmE7hleujQW2jbgIms984Jf6jOcdt2Kie9fNxxIZ1oJnv+MLH7WH7UbT0vfhpX0t40D8oEtWldnkmw9QvAIMwbHkQ3tIENMPfmrna7u6fXNGg9NuoSVxye3zYAr8V9lPVVAAZkD19QtkodYg2R+r3gIQ2NZ5NtRcQPtGVdNM0bJI34jfxnj2PcpobjChOjRiFcYUK5td8uhab8MA848vibnhMFFmZwjVvx3UByeRU2V3Nu2XwwbRj5PQQ0SDga9lT7F1fzYOmqDDuOGBQxGhZzn3ud3WiHTt6B1Fg9ci6659K9GI8GKcBxnkzLhfbgFPthpfoLuxa/mCc0Neeo1X/i6a69kIM6pGMl4djwo8VQw8lvFVpKR8WWuTrqiygpcirOswUP6ZYakK5k5cnQ/WgSqFPxexPI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
